# Generated by Django 4.1.1 on 2022-09-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("admin", "admin"), ("customer", "customer")],
                max_length=100,
                null=True,
            ),
        ),
    ]
