# Generated by Django 4.1.1 on 2023-01-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
