# Generated by Django 4.1.1 on 2022-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_shippingaddress_first_name_shippingaddress_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shippingaddress", old_name="address", new_name="address_line_1",
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="address_line_2",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
