# Generated by Django 4.1.1 on 2022-12-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_address_shippingaddress_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
