# Generated by Django 4.1.1 on 2022-12-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_shippingaddress_address_line_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="state",
            field=models.CharField(
                choices=[("admin", "admin"), ("customer", "customer")], max_length=200
            ),
        ),
    ]
