# Generated by Django 4.1.1 on 2023-01-19 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_shippingaddress_state"),
    ]

    operations = [
        migrations.RemoveField(model_name="shippingaddress", name="first_name",),
        migrations.RemoveField(model_name="shippingaddress", name="last_name",),
    ]
