# Generated by Django 4.1.1 on 2023-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_order_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="first_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="mobile",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
