# Generated by Django 4.1.1 on 2022-09-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.variant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant", unique_together={("product", "variant")},
        ),
    ]
