# Generated by Django 4.1.1 on 2022-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_productvariant_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="description", field=models.TextField(null=True),
        ),
    ]
