# Generated by Django 4.1.1 on 2022-10-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_producttag_product_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="productvariant", unique_together=set(),),
        migrations.AddField(
            model_name="productvariant",
            name="value",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="variant_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.varianttype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "variant_type", "variant_name", "value")},
        ),
        migrations.RemoveField(model_name="productvariant", name="variant",),
    ]
