# Generated by Django 4.1.1 on 2022-10-03 05:11

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Draft", "Draft")],
                default="Active",
                max_length=100,
            ),
        ),
    ]
