# Generated by Django 4.1.1 on 2022-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_productvariant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="available_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="current_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="original_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="total_sales",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="total_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
