# Generated by Django 4.1.1 on 2022-10-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_productvariant_available_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="variant_type",
            field=models.CharField(
                blank=True,
                choices=[("color", "color"), ("other", "other")],
                max_length=100,
                null=True,
            ),
        ),
    ]
