# Generated by Django 4.1.1 on 2022-10-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_alter_productvariant_variant_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productvariant", unique_together={("product", "variant_name")},
        ),
        migrations.AddField(
            model_name="productvariant",
            name="bar_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_bar_code/"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="variant_type",
            field=models.CharField(
                choices=[("color", "color"), ("other", "other")],
                default="other",
                max_length=100,
                null=True,
            ),
        ),
    ]
