# Generated by Django 4.1.1 on 2022-10-07 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0012_alter_productvariant_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
