# Generated by Django 4.1.1 on 2023-01-21 08:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_offer_specialbadge_alter_productvariant_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="table_content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
