# Generated by Django 4.1.1 on 2023-01-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0017_productcategory_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compatibilty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="productvariant",
            name="compatible_with",
            field=models.ManyToManyField(to="inventory.compatibilty"),
        ),
    ]
