# Generated by Django 4.1.1 on 2023-02-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_alter_product_options_coupon"),
    ]

    operations = [
        migrations.RemoveField(model_name="coupon", name="is_active",),
        migrations.AddField(
            model_name="coupon",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="coupon_type",
            field=models.CharField(
                choices=[("percentage", "percentage"), ("cashback", "cashback")],
                default="percentage",
                max_length=200,
            ),
        ),
    ]
