# Generated by Django 4.1.1 on 2023-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_alter_coupon_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon", options={"ordering": ["-status", "-created"]},
        ),
    ]
